browserless-chrome:
  - changed-files:
    -  any-glob-to-any-file: 'charts/browserless-chrome/**/*'

caddy:
  - changed-files:
    -  any-glob-to-any-file: 'charts/caddy/**/*'

dex-k8s-authenticator:
  - changed-files:
    -  any-glob-to-any-file: 'charts/dex-k8s-authenticator/**/*'

kube-secrets-init:
  - changed-files:
    -  any-glob-to-any-file: 'charts/kube-secrets-init/**/*'

rabbitmq-operator:
  - changed-files:
    -  any-glob-to-any-file: 'charts/rabbitmq-operator/**/*'

sftpgo:
  - changed-files:
    -  any-glob-to-any-file: 'charts/sftpgo/**/*'

tusd:
  - changed-files:
    -  any-glob-to-any-file: 'charts/tusd/**/*'
